### PR TITLE
Misc improvements

### PR DESCRIPTION
**Pull request by jcfr**

### CODE REVIEW

**Comment by OlivierLDff** [comment]
Thank you for this pull request i wasn't aware `endif(CONDITION)` isn't the preferred style anymore. Almost all of my CMake files uses the old style. But i'm started to convert on newer projects or when i update some old project. Did you use a tool to concert or have you done it by hand?
Thanks for the contribution!

**Comment by jcfr** [comment]
Thanks for integrating :pray:

**Comment by jcfr** [comment]
> Did you use a tool to concert or have you done it by hand?

These scripts should help, see https://github.com/jcfr/cmake-auto-style#readme

First convert to lowercase, then remove end block.

Let me know if you have any questions,

**Comment by OlivierLDff** [comment]
Ok thank you!

**Pull request merged**
